FROM directus/directus:9.23.1

RUN npm install directus-extension-formula-interface directus-extension-board-layout  directus-extension-currency-interface


# Exts does not work
# RUN npm install directus-extension-linkmeta directus-extension-mass-email
# no npm install
# RUN npm install directus-extension-field-actions directus-interface-qrcode
