FROM directus/directus:latest

RUN npm install directus-extension-computed-interface directus-extension-board-layout  directus-extension-currency-interface directus-extension-mass-email

# Exts does not work
# RUN npm install directus-extension-linkmeta
# no npm install
#RUN npm install directus-extension-field-actions directus-interface-qrcode
