FROM directus/directus:latest

RUN npm install directus-extension-computed-interface directus-extension-board-layout directus-extension-linkmeta directus-extension-currency-interface directus-extension-mass-email

#RUN npm install directus-extension-field-actions directus-interface-qrcode
